#!/usr/bin/env node
// =============================================================================
// i18n-manager.mjs — Manage translation keys in locale files
// =============================================================================
// Source of truth: public/i18n/_src/{locale}/{section}.json (hand-edited).
// Artifacts: public/i18n/{locale}.json (generated by build-i18n.mjs, committed,
// never hand-edited — any manual edit is overwritten by the next build).
//
// Usage:
//   npm run i18n-manager ADD [DRY] <LOCALE> key=value [key2=value2 ...]
//   npm run i18n-manager FILL [DRY] <path-to-json>
//   npm run i18n-manager LIST [LOCALE] path1 [path2 ...]
//   npm run i18n-manager CHECK [JSON]
//
// Subcommands:
//   ADD    Insert one or more keys into a locale's _src fragment (for 1-2 keys).
//          Section = first path segment; a missing fragment file is created.
//   FILL   Batch-insert keys from a JSON file (for large batches).
//          JSON format: { "locale": { "section.key": "value", ... }, ... }
//   LIST   Inspect existing keys. Multiple paths accepted.
//          With a LOCALE: reads the _src fragment. Without: merged monolit view.
//   CHECK  Full verification: missing keys (both directions), unreferenced
//          keys, section/leaf ordering, monolit↔fragment consistency.
//          Add JSON for machine-readable output to node_modules/.tmp/i18n-check.json.
//
// Key format:
//   section.leaf              e.g. register.confirmPassword
//   section.subsection.leaf   e.g. dmca.advanced.claimLabel
//
// Examples:
//   npm run i18n-manager ADD ES register.confirmPassword="Confirmar contraseña"
//   npm run i18n-manager ADD ES dmca.advanced.claimLabel="Reclamación"
//   npm run i18n-manager ADD DRY ES register.confirmPassword="Confirmar contraseña"
//   npm run i18n-manager FILL node_modules/.tmp/i18n-fill.json
//   npm run i18n-manager FILL DRY node_modules/.tmp/i18n-fill.json
//   npm run i18n-manager LIST ES register
//   npm run i18n-manager LIST ES register.confirmPassword register.success
//   npm run i18n-manager LIST ES dmca.advanced
//   npm run i18n-manager LIST dmca.advanced
//   npm run i18n-manager CHECK
//   npm run i18n-manager CHECK JSON
//
// Notes:
//   - Locale codes are case-insensitive: EN, ES, DE, FR, IT, JP, CN, NL, PL, PT, RU, TR
//   - If the key already exists, it is skipped (no overwrite)
//   - After adding, regenerate + verify with: npm run i18n:build && npm run i18n-manager CHECK
// =============================================================================

import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from 'fs';
import { join, dirname, resolve } from 'path';
import { fileURLToPath } from 'url';
import { SECTION_ORDER, KNOWN_LOCALES, sortKeys, assembleMonolit } from './build-i18n.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const I18N_DIR = join(__dirname, '../../public/i18n');
const SRC_DIR = join(I18N_DIR, '_src');
const FRONTEND_DIR = join(__dirname, '../frontend');
const INDEX_HTML = join(__dirname, '../../public/index.html');

const KNOWN_SET = new Set(KNOWN_LOCALES.map((l) => l.toLowerCase()));
const ALL_LOCALES = KNOWN_LOCALES.map((l) => l.toLowerCase());

// Families that are constructed dynamically at runtime and can never be
// enumerated statically — always treated as referenced (PLAN.md §2.3).
const DYNAMIC_FAMILIES = [/^meta\./, /^updates\./, /^cats\./, /^history\.types\./, /^item\.exp/, /^settings\.sharesState_/];

// =============================================================================
// JSON I/O helpers (fragments are the source of truth; monolits are artifacts)
// =============================================================================

function fragmentPath(locale, section) {
	return join(SRC_DIR, locale, `${section}.json`);
}

function loadFragment(locale, section) {
	const filePath = fragmentPath(locale, section);
	if (!existsSync(filePath)) return null;
	try {
		return JSON.parse(readFileSync(filePath, 'utf-8'));
	} catch (e) {
		console.error(`✘ Could not load _src/${locale}/${section}.json: ${e.message}`);
		return null;
	}
}

function saveFragment(locale, section, data, dryRun) {
	const filePath = fragmentPath(locale, section);
	const content = JSON.stringify(sortKeys(data), null, '\t') + '\n';
	if (dryRun) {
		console.log(`  (dry — would write _src/${locale}/${section}.json)`);
	} else {
		mkdirSync(dirname(filePath), { recursive: true });
		writeFileSync(filePath, content, 'utf-8');
	}
}

function loadMonolit(locale) {
	const filePath = join(I18N_DIR, `${locale}.json`);
	try {
		return JSON.parse(readFileSync(filePath, 'utf-8'));
	} catch (e) {
		console.error(`✘ Could not load ${locale}.json: ${e.message}`);
		return null;
	}
}

// =============================================================================
// Object path helpers
// =============================================================================

/**
 * Get nested value by dot-path. Returns undefined if not found.
 */
function getByPath(obj, dotPath) {
	return dotPath.split('.').reduce((acc, k) => acc?.[k], obj);
}

/**
 * Set nested value by dot-path, creating intermediate objects as needed.
 * Returns false if the key already exists (skip), true if inserted.
 */
function setByPath(obj, dotPath, value) {
	const parts = dotPath.split('.');
	const leafKey = parts[parts.length - 1];
	let current = obj;

	for (let i = 0; i < parts.length - 1; i++) {
		const part = parts[i];
		if (current[part] === undefined) {
			current[part] = {};
		} else if (typeof current[part] !== 'object' || current[part] === null) {
			console.error(`  ✘ "${parts.slice(0, i + 1).join('.')}" exists but is not an object.`);
			return false;
		}
		current = current[part];
	}

	if (current[leafKey] !== undefined) {
		return 'skip';
	}

	current[leafKey] = value;
	return true;
}

/**
 * Recursively collect all dot-paths for leaf (string/number) values in an object.
 */
function collectPaths(obj, prefix = '') {
	const paths = [];
	for (const [key, val] of Object.entries(obj)) {
		const full = prefix ? `${prefix}.${key}` : key;
		if (val && typeof val === 'object') {
			paths.push(...collectPaths(val, full));
		} else {
			paths.push(full);
		}
	}
	return paths;
}

/**
 * Recursively collect order violations: at every object level, string leaves
 * must come first (alphabetical) and sub-group objects last (alphabetical).
 * Returns dot-paths of the offending levels.
 */
function collectOrderViolations(obj, prefix = '') {
	const bad = [];
	const actual = Object.keys(obj);
	const expected = Object.keys(sortKeys(obj));
	if (actual.join('\0') !== expected.join('\0')) bad.push(prefix || '(top level)');
	for (const [key, val] of Object.entries(obj)) {
		if (val && typeof val === 'object') bad.push(...collectOrderViolations(val, prefix ? `${prefix}.${key}` : key));
	}
	return bad;
}

// =============================================================================
// LIST mode
// =============================================================================

function runList(locale, paths) {
	// No locale filter — merged monolit view across all locales.
	if (!locale && !paths.length) {
		for (const loc of ALL_LOCALES) {
			const data = loadMonolit(loc);
			if (!data) continue;
			console.log(`[${loc.toUpperCase()}] sections: ${Object.keys(data).join(', ')}`);
		}
		return;
	}

	const readFor = (loc, dotPath) => {
		if (loc) {
			const [section, ...rest] = dotPath.split('.');
			const frag = loadFragment(loc, section);
			if (frag) return rest.length ? getByPath(frag, rest.join('.')) : frag;
		}
		const mono = loadMonolit(loc);
		return mono ? getByPath(mono, dotPath) : undefined;
	};

	if (!paths.length) {
		const data = loadMonolit(locale);
		if (data) console.log(`[${locale.toUpperCase()}] sections: ${Object.keys(data).join(', ')}`);
		return;
	}

	for (const dotPath of paths) {
		console.log(`\n${'─'.repeat(60)}`);
		console.log(`  ${dotPath}`);
		console.log('─'.repeat(60));

		for (const loc of locale ? [locale] : ALL_LOCALES) {
			const val = readFor(loc, dotPath);

			if (val === undefined || val === null) {
				console.log(`  [${loc.toUpperCase()}] ✘ not found`);
			} else if (typeof val === 'object') {
				console.log(`  [${loc.toUpperCase()}]`);
				for (const [k, v] of Object.entries(val)) {
					if (typeof v === 'object') {
						console.log(`    ${k}: { ... }`);
					} else {
						console.log(`    ${k}: '${v}'`);
					}
				}
			} else {
				console.log(`  [${loc.toUpperCase()}] ${dotPath.split('.').pop()}: '${val}'`);
			}
		}
	}
}

// =============================================================================
// ADD mode (writes into _src fragments)
// =============================================================================

function runAdd(map, dryRun) {
	if (dryRun) console.log('Dry run — files will NOT be written.\n');

	let totalWritten = 0,
		totalSkipped = 0,
		totalFailed = 0;

	for (const [locale, entries] of map) {
		console.log(`[${locale.toUpperCase()}]`);
		// Group entries by section (= first path segment) → one fragment each.
		const bySection = new Map();
		for (const e of entries) {
			const section = e.key.split('.')[0];
			if (!bySection.has(section)) bySection.set(section, []);
			bySection.get(section).push(e);
		}

		for (const [section, sectionEntries] of bySection) {
			let data = loadFragment(locale, section);
			const isNew = data === null;
			if (isNew) data = {};
			let modified = false;

			for (const { key, value } of sectionEntries) {
				// Strip the section prefix: the fragment root IS the section.
				const subPath = key.split('.').slice(1).join('.') || key;
				const result = setByPath(data, subPath, value);
				if (result === false) {
					totalFailed++;
				} else if (result === 'skip') {
					console.log(`  ↷ "${key}" already exists — skipped.`);
					totalSkipped++;
				} else {
					console.log(`  ✓ ${key} = '${value}'${isNew && !modified ? ' (new section file)' : ''}`);
					modified = true;
					totalWritten++;
				}
			}

			if (modified) saveFragment(locale, section, data, dryRun);
		}
		console.log('');
	}

	console.log('─────────────────────────────────');
	console.log(`Written: ${totalWritten}  Skipped: ${totalSkipped}  Failed: ${totalFailed}`);
	if (!dryRun && totalWritten > 0) console.log('\nRegenerate + verify: npm run i18n:build && npm run i18n-manager CHECK');
}

// =============================================================================
// FILL mode — batch-insert from JSON file (same fragment routing as ADD)
// =============================================================================

function runFill(filePath, dryRun) {
	const absPath = resolve(filePath);
	if (!existsSync(absPath)) {
		console.error(`✘ File not found: ${absPath}`);
		process.exit(1);
	}

	let json;
	try {
		json = JSON.parse(readFileSync(absPath, 'utf-8'));
	} catch (e) {
		console.error(`✘ Invalid JSON: ${e.message}`);
		process.exit(1);
	}

	if (typeof json !== 'object' || json === null || Array.isArray(json)) {
		console.error('✘ JSON must be an object: { "locale": { "section.key": "translated value", ... }, ... }');
		process.exit(1);
	}

	if (dryRun) console.log('Dry run — files will NOT be written.\n');

	// Build the same Map structure that runAdd expects
	const map = new Map();
	for (const [locale, keys] of Object.entries(json)) {
		const loc = locale.toLowerCase();
		if (!KNOWN_SET.has(loc)) {
			console.warn(`  ⚠ Unknown locale "${locale}" — skipped.`);
			continue;
		}
		if (typeof keys !== 'object' || keys === null || Array.isArray(keys)) {
			console.warn(`  ⚠ Locale "${locale}" value must be an object — skipped.`);
			continue;
		}
		const entries = [];
		for (const [key, value] of Object.entries(keys)) {
			if (typeof value !== 'string') {
				console.warn(`  ⚠ [${loc}] "${key}" value is not a string — skipped.`);
				continue;
			}
			entries.push({ key, value });
		}
		if (entries.length) map.set(loc, entries);
	}

	if (!map.size) {
		console.error('✘ No valid entries found in JSON.');
		process.exit(1);
	}

	runAdd(map, dryRun);
}

// =============================================================================
// CHECK mode — missing (both directions) + unreferenced + order + consistency
// =============================================================================

// A candidate reference only counts when its first segment is a known section;
// this rejects non-i18n string literals (brand names, host patterns, …).
function validRef(candidate, sections) {
	if (!candidate || !candidate.includes('.') || candidate.includes('${')) return false;
	return sections.has(candidate.split('.')[0]);
}

function collectCodeRefs(sections) {
	const refs = new Set();
	const files = [];
	const walk = (dir) => {
		for (const f of readdirSync(dir, { withFileTypes: true })) {
			const p = join(dir, f.name);
			if (f.isDirectory()) walk(p);
			else if (p.endsWith('.ts')) files.push(p);
		}
	};
	walk(FRONTEND_DIR);
	files.push(INDEX_HTML);

	const reT = /\bt\s*\(\s*['"`]([^'"`]+)['"`]/g;
	// Any object-literal `word: 'dotted.path'` (titleKey/label/key/title/countKey/
	// emptyKey/too_long/… — the property name is irrelevant; the section gate in
	// validRef rejects non-i18n string literals such as brand names).
	const reKey = /(?:^|[{}\s,])([A-Za-z_$][\w$]*)\s*:\s*['"]([^'"]+)['"]/g;
	const reData = /data-i18n\s*=\s*['"]([^'"]+)['"]/g;

	for (const f of files) {
		let s;
		try {
			s = readFileSync(f, 'utf-8');
		} catch {
			continue;
		}
		let m;
		while ((m = reT.exec(s))) if (validRef(m[1], sections)) refs.add(m[1]);
		while ((m = reKey.exec(s))) if (validRef(m[2], sections)) refs.add(m[2]);
		while ((m = reData.exec(s))) if (validRef(m[1], sections)) refs.add(m[1]);
	}
	return refs;
}

async function runCheck(jsonMode) {
	const monolits = {};
	for (const loc of ALL_LOCALES) {
		const parsed = loadMonolit(loc);
		if (parsed) monolits[loc] = parsed;
	}

	const ref = monolits['en'];
	if (!ref) {
		console.error('Could not load en.json as reference.');
		process.exit(1);
	}

	const enPaths = collectPaths(ref);
	const enSet = new Set(enPaths);
	const sections = new Set(Object.keys(ref));

	// 1. Missing in other locales (EN → others).
	const missing = [];
	for (const dotPath of enPaths) {
		const absentIn = [];
		for (const loc of ALL_LOCALES) {
			if (loc === 'en') continue;
			if (!monolits[loc]) continue;
			if (getByPath(monolits[loc], dotPath) === undefined) absentIn.push(loc);
		}
		if (absentIn.length) missing.push({ dotPath, absentIn });
	}

	// 2. Present elsewhere but missing in EN (others → EN).
	const missingInEn = [];
	{
		const seen = new Set();
		for (const loc of ALL_LOCALES) {
			if (loc === 'en' || !monolits[loc]) continue;
			for (const dotPath of collectPaths(monolits[loc])) {
				if (seen.has(dotPath) || enSet.has(dotPath)) continue;
				seen.add(dotPath);
				const presentIn = ALL_LOCALES.filter((l) => l !== 'en' && monolits[l] && getByPath(monolits[l], dotPath) !== undefined);
				missingInEn.push({ dotPath, presentIn });
			}
		}
		missingInEn.sort((a, b) => (a.dotPath < b.dotPath ? -1 : 1));
	}

	// 3. Unreferenced keys (in EN, never reached via any t() channel).
	const unreferenced = [];
	{
		const refs = collectCodeRefs(sections);
		for (const dotPath of enPaths) {
			if (refs.has(dotPath)) continue;
			if (DYNAMIC_FAMILIES.some((re) => re.test(dotPath))) continue;
			unreferenced.push(dotPath);
		}
		unreferenced.sort();
	}

	// 4. Order violations (layered sections, alphabetical leaves, groups last).
	const orderIssues = [];
	{
		const expectedTop = SECTION_ORDER.filter((s) => ref[s] !== undefined);
		for (const loc of ALL_LOCALES) {
			if (!monolits[loc]) continue;
			const actualTop = Object.keys(monolits[loc]);
			const knownActual = actualTop.filter((s) => SECTION_ORDER.includes(s));
			const expectedKnown = expectedTop.filter((s) => knownActual.includes(s));
			if (knownActual.join('\0') !== expectedKnown.join('\0'))
				orderIssues.push(`${loc}: top-level section order`);
			for (const bad of collectOrderViolations(monolits[loc])) {
				if (bad !== '(top level)') orderIssues.push(`${loc}: unordered keys in ${bad}`);
			}
		}
		orderIssues.sort();
	}

	// 5. Monolit↔fragment consistency (regenerate in memory, compare bytes).
	const inconsistent = [];
	for (const loc of ALL_LOCALES) {
		let expected;
		try {
			expected = assembleMonolit(loc);
		} catch (e) {
			orderIssues.push(`${loc}: cannot assemble fragments (${e.message})`);
			continue;
		}
		let actual;
		try {
			actual = readFileSync(join(I18N_DIR, `${loc}.json`), 'utf-8');
		} catch {
			continue;
		}
		if (actual !== expected) inconsistent.push(loc);
	}
	inconsistent.sort();

	const failed = missing.length + missingInEn.length + unreferenced.length + orderIssues.length + inconsistent.length;

	if (jsonMode) {
		const out = {
			total: failed,
			missing: missing.map(({ dotPath, absentIn }) => ({
				key: dotPath,
				locales: absentIn,
				en: String(getByPath(ref, dotPath) ?? ''),
			})),
			missingInEn: missingInEn.map(({ dotPath, presentIn }) => ({ key: dotPath, presentIn })),
			unreferenced,
			orderIssues,
			inconsistent,
		};
		mkdirSync(join(__dirname, '../../node_modules/.tmp'), { recursive: true });
		const outPath = join(__dirname, '../../node_modules/.tmp/i18n-check.json');
		writeFileSync(outPath, JSON.stringify(out, null, 2), 'utf-8');
		if (!failed) console.log('✔ All keys present in all locales.');
		else {
			console.log(`✘ ${failed} i18n issues → ${outPath}`);
			process.exit(1);
		}
		return;
	}

	if (!failed) {
		console.log('✔ All keys present in all locales.');
		return;
	}

	if (missing.length) {
		console.log(`Missing keys (${missing.length}):`);
		for (const { dotPath, absentIn } of missing) console.log(`  ${dotPath}: ${absentIn.join(', ')}`);
	}
	if (missingInEn.length) {
		console.log(`Present elsewhere but missing in EN (${missingInEn.length}):`);
		for (const { dotPath, presentIn } of missingInEn) console.log(`  ${dotPath}: in ${presentIn.join(', ')}`);
	}
	if (unreferenced.length) {
		console.log(`Unreferenced keys (${unreferenced.length}):`);
		for (const k of unreferenced) console.log(`  ${k}`);
	}
	if (orderIssues.length) {
		console.log(`Order issues (${orderIssues.length}):`);
		for (const k of orderIssues) console.log(`  ${k}`);
	}
	if (inconsistent.length) {
		console.log(`Monolits out of sync with _src (${inconsistent.length}): ${inconsistent.join(', ')}`);
		console.log('  Run: npm run i18n:build');
	}
	console.log(`\nTotal: ${failed} i18n issues across ${ALL_LOCALES.length} locales.`);
	process.exit(1);
}

// =============================================================================
// Argument parsers
// =============================================================================

function parseAddArgs(args) {
	const map = new Map();
	let currentLocale = null;
	let dryRun = false;

	for (const arg of args) {
		if (arg.toUpperCase() === 'DRY') {
			dryRun = true;
			continue;
		}

		if (KNOWN_SET.has(arg.toLowerCase()) && !arg.includes('=')) {
			currentLocale = arg.toLowerCase();
			if (!map.has(currentLocale)) map.set(currentLocale, []);
			continue;
		}

		const eqIdx = arg.indexOf('=');
		if (eqIdx === -1) {
			console.warn(`Warning: ignored "${arg}"`);
			continue;
		}

		if (!currentLocale) {
			console.error(`Error: key=value "${arg}" before a locale code. Valid: ${ALL_LOCALES.join(', ')}`);
			process.exit(1);
		}

		map.get(currentLocale).push({ key: arg.slice(0, eqIdx).trim(), value: arg.slice(eqIdx + 1).trim() });
	}

	return { map, dryRun };
}

function parseListArgs(args) {
	let locale = null;
	const paths = [];

	for (const arg of args) {
		if (KNOWN_SET.has(arg.toLowerCase()) && !arg.includes('.')) {
			locale = arg.toLowerCase();
		} else {
			paths.push(arg);
		}
	}

	return { locale, paths };
}

// =============================================================================
// Main
// =============================================================================

const args = process.argv.slice(2);
const subcommand = args[0]?.toUpperCase();

if (!subcommand || subcommand === 'HELP') {
	printHelp();
	process.exit(0);
}

if (subcommand === 'LIST') {
	const { locale, paths } = parseListArgs(args.slice(1));
	runList(locale, paths);
} else if (subcommand === 'ADD') {
	const { map, dryRun } = parseAddArgs(args.slice(1));
	if (!map.size) {
		printHelp();
		process.exit(0);
	}
	runAdd(map, dryRun);
} else if (subcommand === 'FILL') {
	const rest = args.slice(1);
	const dryRun = rest[0]?.toUpperCase() === 'DRY';
	const filePath = dryRun ? rest[1] : rest[0];
	if (!filePath) {
		console.error('Error: FILL requires a JSON file path.');
		printHelp();
		process.exit(1);
	}
	runFill(filePath, dryRun);
} else if (subcommand === 'CHECK') {
	const jsonMode = args.slice(1).some((a) => a.toUpperCase() === 'JSON');
	await runCheck(jsonMode);
} else {
	console.error(`Unknown subcommand "${args[0]}". Use ADD, FILL, LIST, or CHECK.`);
	printHelp();
	process.exit(1);
}

function printHelp() {
	console.log(`i18n-manager — manage translation keys in locale files

Source of truth: public/i18n/_src/{locale}/{section}.json
Artifacts: public/i18n/{locale}.json (regenerate with npm run i18n:build)

Usage:
  npm run i18n-manager ADD [DRY] <LOCALE> key=value [key2=value2 ...]
  npm run i18n-manager FILL [DRY] <path-to-json>
  npm run i18n-manager LIST [LOCALE] [path1 path2 ...]
  npm run i18n-manager CHECK [JSON]

Locale codes (case-insensitive): EN ES DE FR IT JP CN NL PL PT RU TR

Key format:
  section.leaf               register.confirmPassword
  section.subsection.leaf    dmca.advanced.claimLabel

FILL JSON format:
  { "locale": { "section.key": "translated value", ... }, ... }

Examples:
  npm run i18n-manager ADD ES register.confirmPassword="Confirmar contraseña"
  npm run i18n-manager ADD DRY ES register.confirmPassword="Confirmar contraseña"
  npm run i18n-manager FILL node_modules/.tmp/i18n-fill.json
  npm run i18n-manager FILL DRY node_modules/.tmp/i18n-fill.json
  npm run i18n-manager LIST ES register
  npm run i18n-manager LIST dmca.advanced
  npm run i18n-manager CHECK
  npm run i18n-manager CHECK JSON
`);
}
